
services:
  backend:
    container_name: teta-backend
    build:
      context: ./teta-backend
      dockerfile: Dockerfile
#      target: production
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./teta-backend:/usr/src/app
      - /usr/src/app/node_modules
    env_file: .env
    depends_on:
      - db
    networks:
      - teta-network
    mem_limit: 512m      # حداکثر 512 مگابایت RAM
    cpus: 0.5 

  db:
    container_name: teta-db
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "127.0.0.1:55432:5432"
    volumes:
      - teta-db-data:/var/lib/postgresql/data
    networks:
      - teta-network
    deploy:
      resources:
        limits:
          memory: 1024M
          cpus: "0.50"         # حداکثر 50% از یک هسته
        reservations:
          memory: 256M
          cpus: "0.20"         # حداقل نیاز به 25% از یک

networks:
  teta-network:
    driver: bridge

volumes:
  teta-db-data:
    driver: local
